input_config:
  bed_files:
    - path: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/data/mm10_atac_seq/E11.5_XX_Enh8-mCherry_consensus_peaks_2rep_normalized.bed
      name: "E11.5.XX"
      extra_columns: null
    - path: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/data/mm10_atac_seq/E11.5_XY_Sox9-IRES-GFP_consensus_peaks_2rep_normalized.bed
      name: "E11.5.XY"
      extra_columns: null
    - path: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/data/mm10_atac_seq/E12.5_XX_Enh8-mCherry_consensus_peaks_2rep_normalized.bed
      name: "E12.5.XX"
      extra_columns: null
    - path: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/data/mm10_atac_seq/E12.5_XY_Sox9-IRES-GFP_consensus_peaks_2rep_normalized.bed
      name: "E12.5.XY"
      extra_columns: null
    - path: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/data/mm10_atac_seq/E13.5_XX_Enh8-mCherry_consensus_peaks_2rep_normalized.bed
      name: "E13.5.XX"
      extra_columns: null
    - path: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/data/mm10_atac_seq/E13.5_XY_Sox9-IRES-GFP_consensus_peaks_2rep_normalized.bed
      name: "E13.5.XY"
      extra_columns: null
    - path: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/data/mm10_atac_seq/E15.5_XX_Enh8-mCherry_consensus_peaks_2rep_normalized.bed
      name: "E15.5.XX"
      extra_columns: null
    - path: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/data/mm10_atac_seq/E15.5_XY_Sox9-IRES-GFP_consensus_peaks_2rep_normalized.bed
      name: "E15.5.XY"
      extra_columns: null
  refseq_gtf: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/results/old_results/mice_mm10_atac_seq_bed_Files/iGenome_mm10_ucsc_genes.gtf
  coding_bed: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/results/mm10_yaml_run/mm10_coding_regions_refseq.bed
  copy_input: true
  add_id: true
  id_column_name: id

output_dir: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/results/mm10_yaml_run
genome_build: mm10
tmp_dir: /tmp

merge:
  enabled: true
  out_path: /home/ls/toozig/gonen-lab/users/toozig/projects/dsd-viz/bed_file_merger/results/mm10_yaml_run/merged_inputs.bed
  bedtools_opts: ""
